version: "3.3"

services:
  activemq:
    image: vromero/activemq-artemis:latest-alpine
    container_name: activemq
    environment:
      ARTEMIS_USERNAME: guest
      ARTEMIS_PASSWORD: guest
    ports:
      - 8161:8161
      - 61616:61616